from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
             path('graph/<str:dataName>/<str:timeGroup>/<str:noWeekend>/<str:minZero>/<str:graphType>/<str:normalizeData>/', views.refreshGraph, name='refreshGraph'),
             path('rps/<int:gameId>/', views.returnGameState, name='returnGameState'),
             path('rps/<int:gameId>/left/<int:handCode>/', views.setLeft, name='setLeft'),
             path('rps/<int:gameId>/right/<int:handCode>/', views.setRight, name='setRight'),
             path('rps/<int:gameId>/evaluate/', views.evaluate, name='evaluateGame'),
             path('rps/<int:gameId>/reset/', views.reset, name='resetGame'),
             path('rps/<int:gameId>/checkId/', views.checkId, name='checkId'),
             path('rps/createGame/', views.createGame, name='createGame'),
             path('', views.index, name='index'),
             path('loveletter/creategame/<int:numberOfPlayers>/', views.createLoveLetterGame, name='createGameLoveLetter'),
             path('loveletter/gamestate/<int:gameId>/', views.loveLetterReturnGameState, name='loveLetterGameState'),
             path('loveletter/advanceturn/<int:gameId>/', views.advanceTurnLoveLetter, name='loveLetterAdvanceTurn'),
             path('loveletter/deal/<int:gameId>/<int:numberOfPlayers>/<int:deckNumber>', views.dealLoveLetter, name='loveLetterDeal'),
             path('loveletter/playCard/<int:gameId>/<str:card>/<int:playerNumber>/<int:target>/<str:guardGuess>/', views.playCardLoveLetter, name='loveLetterPlayCard'),
             path('loveletter/<int:gameId>/checkId/', views.checkIdLoveLetter, name='checkIdLoveLetter'),
             path('loveletter/<int:gameId>/resetGame/<int:deckNumber>/', views.resetGameLoveLetter, name='resetGameLoveLetter'),
             path('loveletter/resettests/', views.resetTestsLoveLetter, name='resetTestsLoveLetter'),
             path('shogun/creategame/', views.createGameShogun, name='createGameShogun'),
             path('shogun/resetgame/<int:gameId>/<int:numberPlayers>/', views.resetGameShogun, name='resetGameShogun'),
             path('shogun/gamestate/<int:gameId>/', views.gameStateShogun, name='gameStateShogun'),
             path('shogun/roll/<int:gameId>/<int:playerNumber>/', views.rollShogun, name='rollShogun'),
             path('shogun/<int:gameId>/checkId/', views.checkIdShogun, name='checkIdShogun'),
             path('shogun/<int:gameId>/toggleSave/<int:saveIndex>/', views.toggleSaveShogun, name='toggleSaveShogun'),
             path('shogun/<int:gameId>/resolveroll/', views.resolveRollShogun, name='resolveRollShogun'),
             path('shogun/<int:gameId>/buy/<int:buyNumber>/', views.buyShogun, name='buyShogun'),
             path('shogun/<int:gameId>/doneyielding/', views.doneYieldingShogun, name='doneYieldingShogun'),
             path('shogun/<int:gameId>/setmaxhealth/<int:maxHealth>/', views.setMaxHealthShogun, name='maxHealthShogun'),
             path('shogun/<int:gameId>/setmaxvictory/<int:maxVictory>/', views.setMaxVictoryShogun, name='maxVictoryShogun'),
             path('shogun/<int:gameId>/yieldedo/<str:edoString>/', views.yieldEdoShogun, name='yieldEdoShogun'),
             path('shogun/<int:gameId>/clearbuy/', views.clearBuyShogun, name='clearBuyShogun'),
             path('shogun/resettests/', views.resetTestsShogun, name='resetTestsShogun'),
             path('shogun/<int:gameId>/setdice/<str:diceCode>/', views.setDiceShogun, name='setDiceShogun'),
             path('deepsea/creategame/', views.createGameDeepSea, name='createGameDeepSea'),
             path('deepsea/resetgame/<int:gameId>/<int:numberPlayers>/', views.resetGameDeepSea, name='resetGameDeepSea'),
             path('deepsea/gamestate/<int:gameId>/', views.gameStateDeepSea, name='gameStateDeepSea'),
             path('deepsea/<int:gameId>/checkId/', views.checkIdDeepSea, name='checkIdDeepSea'),
             path('deepsea/changedirection/<int:gameId>/<int:playerNumber>/<int:isChangingDirection>/', views.changeDirectionDeepSea, name='changeDirectionDeepSea'),
             path('deepsea/roll/<int:gameId>/', views.rollDeepSea, name='rollDeepSea'),
             path('deepsea/taketreasure/<int:gameId>/', views.takeTreasureDeepSea, name='takeTreasureDeepSea'),
             path('deepsea/advanceturn/<int:gameId>/', views.advanceTurnDeepSea, name='advanceTurnDeepSea'),
             path('deepsea/droptreasure/<int:gameId>/', views.dropTreasureDeepSea, name='dropTreasureDeepSea'),
             path('deepsea/spoofdice/<int:gameId>/<int:diceValue>/', views.spoofDiceDeepSea, name='spoofDiceDeepSea'),
             path('deepsea/resettests/', views.resetTestsDeepSea, name='resetTestsDeepSea'),
             path('deepsea/resettests/', views.resetTestsDeepSea, name='resetTestsDeepSea'),
             path('deepsea/setmaxoxygen/<int:gameId>/<int:maxOxygen>/', views.setMaxOxygenDeepSea, name='setMaxOxygenDeepSea'),
             path('deepsea/setmaxrounds/<int:gameId>/<int:maxRounds>/', views.setMaxRoundsDeepSea, name='setMaxRoundsDeepSea'),
             ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)