# Generated by Django 3.2.6 on 2021-08-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RPSGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftHand', models.CharField(max_length=30)),
                ('rightHand', models.CharField(max_length=30)),
                ('win', models.CharField(max_length=30)),
            ],
        ),
    ]
