# Generated by Django 3.2.6 on 2021-08-25 17:07

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_lovelettergame'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovelettergame',
            name='currentTurn',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lovelettergame',
            name='deck',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), default=['none'], max_length=336, size=16),
        ),
        migrations.AddField(
            model_name='lovelettergame',
            name='drawCard',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='lovelettergame',
            name='hands',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), default=['none'], max_length=126, size=6),
        ),
    ]
