# Generated by Django 3.2.6 on 2021-08-25 17:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_auto_20210825_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovelettergame',
            name='isDisplayed',
            field=django_mysql.models.ListCharField(models.IntegerField(default=0), default=[0], max_length=6, size=10),
        ),
        migrations.AddField(
            model_name='lovelettergame',
            name='isHandMaiden',
            field=django_mysql.models.ListCharField(models.IntegerField(default=0), default=[0], max_length=6, size=10),
        ),
        migrations.AddField(
            model_name='lovelettergame',
            name='message',
            field=django_mysql.models.ListCharField(models.CharField(max_length=40), default=['none'], max_length=246, size=6),
        ),
        migrations.AddField(
            model_name='lovelettergame',
            name='playersInGame',
            field=django_mysql.models.ListCharField(models.IntegerField(default=1), default=[1], max_length=6, size=10),
        ),
        migrations.AddField(
            model_name='lovelettergame',
            name='setAsideCard',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
