# Generated by Django 3.2.6 on 2021-08-25 17:17

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0004_auto_20210825_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='lovelettergame',
            name='playedCards',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), default=[], max_length=336, size=16),
        ),
        migrations.AddField(
            model_name='lovelettergame',
            name='totalNumberOfPlayers',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='lovelettergame',
            name='useDefaultDeck',
            field=models.BooleanField(default=False),
        ),
    ]
