# Generated by Django 3.2.6 on 2021-08-25 17:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0005_auto_20210825_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovelettergame',
            name='deck',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), default=['guard', 'guard', 'guard', 'guard', 'guard', 'priest', 'priest', 'baron', 'baron', 'handmaiden', 'handmaiden', 'prince', 'prince', 'king', 'countess', 'princess'], max_length=336, size=16),
        ),
        migrations.AlterField(
            model_name='lovelettergame',
            name='hands',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), default=['none', 'none', 'none', 'none'], max_length=126, size=6),
        ),
        migrations.AlterField(
            model_name='lovelettergame',
            name='isDisplayed',
            field=django_mysql.models.ListCharField(models.IntegerField(default=0), default=[0, 0, 0, 0, 0, 0], max_length=6, size=10),
        ),
        migrations.AlterField(
            model_name='lovelettergame',
            name='isHandMaiden',
            field=django_mysql.models.ListCharField(models.IntegerField(default=0), default=[0, 0, 0, 0], max_length=6, size=10),
        ),
        migrations.AlterField(
            model_name='lovelettergame',
            name='message',
            field=django_mysql.models.ListCharField(models.CharField(max_length=40), default=['blank message', 'blank message', 'blank message', 'blank message', 'blank message', 'blank message'], max_length=246, size=6),
        ),
        migrations.AlterField(
            model_name='lovelettergame',
            name='playersInGame',
            field=django_mysql.models.ListCharField(models.IntegerField(default=1), default=[1, 2, 3, 4], max_length=6, size=10),
        ),
        migrations.AlterField(
            model_name='lovelettergame',
            name='useDefaultDeck',
            field=models.BooleanField(default=True),
        ),
    ]
