# Generated by Django 3.2.6 on 2021-08-25 17:41

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0006_auto_20210825_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovelettergame',
            name='isDisplayed',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1), default=['0', '0', '0', '0'], max_length=10, size=5),
        ),
        migrations.AlterField(
            model_name='lovelettergame',
            name='isHandMaiden',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1), default=['0', '0', '0', '0'], max_length=10, size=5),
        ),
        migrations.AlterField(
            model_name='lovelettergame',
            name='playersInGame',
            field=django_mysql.models.ListCharField(models.CharField(max_length=5), default=['1', '2', '3', '4'], max_length=36, size=6),
        ),
    ]
