# Generated by Django 3.2.6 on 2021-08-29 20:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0007_auto_20210825_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovelettergame',
            name='isDisplayed',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1), default=['0', '0', '0', '0', '0', '0'], max_length=12, size=6),
        ),
    ]
