# Generated by Django 3.2.6 on 2021-08-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0008_alter_lovelettergame_isdisplayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovelettergame',
            name='currentTurn',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
