# Generated by Django 3.2.6 on 2021-08-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0009_alter_lovelettergame_currentturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovelettergame',
            name='currentTurn',
            field=models.IntegerField(default=1),
        ),
    ]
