# Generated by Django 3.2.6 on 2021-08-30 17:04

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0010_alter_lovelettergame_currentturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovelettergame',
            name='message',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=['blank message', 'blank message', 'blank message', 'blank message', 'blank message', 'blank message'], max_length=606, size=6),
        ),
    ]
