# Generated by Django 3.2.6 on 2021-09-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0012_shogun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shogun',
            name='notDirectUseHands',
            field=models.JSONField(default=dict),
        ),
    ]
