# Generated by Django 3.2.6 on 2021-09-01 15:27

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0013_alter_shogun_notdirectusehands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shogun',
            old_name='notDirectUseHands',
            new_name='hands',
        ),
        migrations.AddField(
            model_name='shogun',
            name='bayEdo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shogun',
            name='buttonPhase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shogun',
            name='buyCards',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='shogun',
            name='canBuy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shogun',
            name='canYield',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shogun',
            name='deck',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='shogun',
            name='doShuffle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shogun',
            name='edo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shogun',
            name='maxHealth',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='shogun',
            name='maxPlayers',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='shogun',
            name='message',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=['blank message', 'blank message', 'blank message', 'blank message', 'blank message', 'blank message'], max_length=606, size=6),
        ),
        migrations.AddField(
            model_name='shogun',
            name='notDirectUseHealth',
            field=django_mysql.models.ListCharField(models.CharField(max_length=2), default=['0', '0', '0', '0'], max_length=18, size=6),
        ),
        migrations.AddField(
            model_name='shogun',
            name='notDirectUsePoints',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1), default=['0', '0', '0', '0'], max_length=12, size=6),
        ),
        migrations.AddField(
            model_name='shogun',
            name='remainingRolls',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='shogun',
            name='startEnergy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shogun',
            name='winPoints',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='shogun',
            name='withSpoof',
            field=models.BooleanField(default=False),
        ),
    ]
