# Generated by Django 3.2.6 on 2021-09-01 15:56

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0015_rename_notdirectusedice_shogun_notdirectusesaved'),
    ]

    operations = [
        migrations.AddField(
            model_name='shogun',
            name='notDirectUseEnergy',
            field=django_mysql.models.ListCharField(models.CharField(max_length=2), default=['0', '0', '0', '0'], max_length=18, size=6),
        ),
    ]
