# Generated by Django 3.2.6 on 2021-09-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0016_shogun_notdirectuseenergy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shogun',
            new_name='ShogunGame',
        ),
    ]
