# Generated by Django 3.2.6 on 2021-09-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0017_rename_shogun_shogungame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shogungame',
            name='buyCards',
        ),
    ]
