# Generated by Django 3.2.6 on 2021-09-07 17:56

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0019_alter_shogungame_notdirectusesaved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovelettergame',
            name='isDisplayed',
            field=django_mysql.models.ListCharField(models.CharField(max_length=1), default=['0', '0', '0', '0', '0', '0'], max_length=20, size=10),
        ),
    ]
