# Generated by Django 3.2.6 on 2021-09-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0020_alter_lovelettergame_isdisplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shogungame',
            name='isGameOver',
            field=models.BooleanField(default=True),
        ),
    ]
