# Generated by Django 3.2.6 on 2021-09-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0021_shogungame_isgameover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shogungame',
            name='isGameOver',
            field=models.BooleanField(default=False),
        ),
    ]
