# Generated by Django 3.2.7 on 2021-09-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0023_auto_20210915_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepseagame',
            name='doRemove',
            field=models.BooleanField(default=False),
        ),
    ]
