# Generated by Django 3.2.7 on 2021-09-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0024_deepseagame_doremove'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deepseagame',
            old_name='heldTreasures',
            new_name='heldTreasure',
        ),
    ]
